### ISSUE TITLE
pyproj will not compile using Microsoft Compiler for Python 2.7

### ISSUE THREAD

**Issue by PaulPorthouse** [jswhit/pyproj#42]
It appears that the Microsoft Compiler for Python 2.7 
doesn't like the warning pragma and raises a fatal error while compiling when trying to install using pip.

```
C:\Users\ishare\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Isrc -IC:\Python27\include -IC:\Python27\PC /Tcsrc\pj_strtod.c /Fobuild\temp.win32-2.7\Release\src\pj_strtod.obj
pj_strtod.c
src\pj_strtod.c(79) : fatal error C1021: invalid preprocessor command 'warning'
error: command 'C:\\Users\\ishare\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2
```

I have locally commented out the [offending line](https://github.com/jswhit/pyproj/blob/master/src/pj_strtod.c#L79), and then successfully installed it using pip.

[Failed install log](https://github.com/jswhit/pyproj/files/79963/install.txt)

**Comment by micahcochran** [comment]
This issue needs to be submitted to [OSGeo/proj.4](https://github.com/OSGeo/proj.4).  That is where proj.4 code is maintained.  Pyproj contains a copy of proj.4 source code.

As you identified, Visual C++ doesn't support `#warning` directive. For Visual C++ it looks like it should be `#pragma message("localeconv not available") `. 

It looks like it will be simple to fix, but it will probably continue to cause problems for Windows the new 1.9.5 release of pyproj.  

Perhaps [AppVeyor-CI](https://www.appveyor.com/) could be used to address issues on compiling on Windows.

**Comment by PaulPorthouse** [comment]
Many thanks, will do.

**Comment by jswhit** [comment]
Another option would be to uncomment the line

    #macros.append(('HAVE_STRERROR',1))

in setup.py.

**Comment by micahcochran** [comment]
[A pull request patching the `#warning` statement this was merged into proj.4.](https://github.com/OSGeo/proj.4/pull/342)

**Comment by jswhit** [comment]
I've merged the updated pj_strtod.c into pyproj master.  Do we need a new release (1.9.5.1)?

**Comment by ocefpaf** [comment]
I copied the patch to my [conda package](https://github.com/conda-forge/staged-recipes/pull/41/files) but a new release would be nice.

**Comment by micahcochran** [comment]
It looks like there are a few [repositories dependent of pyproj](https://libraries.io/pypi/pyproj).  On Windows, as is this will probably breaking new installation of basemap or geopandas on Windows.  It would probably be cleaner to have a new release.

Sorry, I should have caught this.

**Comment by ocefpaf** [comment]
> Sorry, I should have caught this.

No problem.  I can help you later to set AppVeyor up.

**Comment by jswhit** [comment]
1.9.5.1 release now on pypi

**Comment by ocefpaf** [comment]
Thanks again!
